### ISSUE TITLE
Improve projectile rendering

### ISSUE THREAD

**Issue by toberge** [hackerspace-ntnu/Prosjekt-Spill-H22#76]
Two visual effect systems:

- One for bullet path that controls the trail
- One for the bullet trails, displaying a limited amount of bullet trails following the bullets

**Comment by Fueredoriku** [comment]
Make gun only have 1 emitter PER bullet-effect instead of 1 per bullet in the scene. Eg.: 1 particle emitter per effect which then render every bullet.

We can have 1 million particles, but we can't have 1 million particle emitters.

Bad performance:
![image](https://user-images.githubusercontent.com/54811121/219115938-da5e9828-eb8b-4aed-9203-1fcaccde0bee.png)
Good performance:
![image](https://user-images.githubusercontent.com/54811121/219116088-7249e3c2-548f-4d2c-985b-75ca736ac4f1.png)
